# Site settings
title: Ricardo Loo Foronda
description: 'Google Cloud Platform'
url: https://www.ricalo.com
google_analytics: UA-58617540-4
feed_icon: false
# disqus_shortname: 'your-disqus-name'

author:
  name: Ricardo Loo Foronda
  email: me@ricalo.com
  twitter_username: ricalo
  github_username:  ricalo
  linkedin_username:  ricalo

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

repository: ricalo/ricalo.github.io

sass:
  style: compressed
  sass_dir: _sass

exclude: ['.well-known']
keep_files: ['.well-known']
